trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.12'
  displayName: 'Install Python'

- script: |
    python --version
  displayName: 'Check Python Version'

- script: |
    pip install tkinter
  displayName: 'Install Tkinter'

- script: |
    python -m py_compile app.py
  displayName: 'Check Python Errors'

- script: |
    python app.py
  displayName: 'Run Charity Fund System'
